name: PlatformIO
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: PlatformIO Run
        uses: karniv00l/platformio-run-action@0.1.0